language: python
python: 3.6
git:
  depth: false
install:
- pip install -r permproject/requirements/reqs.txt
script:
- pylint --load-plugins=pylint_django **/*.py
- coverage run manage.py test
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  user: ssys
  password:
    secure: MD/NIxEIoVXZEXQ/b/xiYQgZuMSoKDgX9sDYBVFNcOiShEv6NklVIzv4sMYkaF6vYWsO+gdgFKZeyYvk4OPy87zjJmyztXiiXjpsTHT3+Z5ZG/YzBd6XKzhh3Xk8mgiUbYEAWzNBqM42BdjrJ0lH3HXFyZtW1XvtLjLcCzT2by+EGdOI8BxBA0ZEAQo7kCRfk3OXAFwAnl/hYy115VxTck7whbwU9fDniro5JT9IiIEO8KmaSN8lKbvM58VR1H/+fTLiryd2H+OiGCKLCmsp0KkPgyQ0Dcat3o4WlsDvaMWxvQbE+ycXkoT/EElVNsB6iMj2fZIlzNt2tDaHMQ6bB9Re/hvxTTDlPgVbONsiG4ZGVwdDF9W1gqiEaRnwUqVtExMWsyxkQkhhs57Pv03weLADkt6cHmHmAkqs1bhBMBmdg3UA/h1hODT9FiE+5Ry76AFele0iG0ILz316URPgEjwuFsSi4kMbnpVhK3nBFBjCiQZSdK6ibWjtqCe4l2IoWtLNV/64epGk5wG+hamNn9md2eE7tiqmiy2+0wAEzO4fyWq4n1YZCWj3cvCgcVFpOwJXKx4cNCAUeiCk1uuuceyJ+y+dxo38kMKtAVerSI2sitJd3n6pF1pK0mTAr4iMz+DtZ1D09IGGBUCrlur3eBE56pYPg++2/3jOugoW/f8=
  on:
    branch: master
    tags: true
